vert_min = [(0, 1), (0, 2), (0, 3)]
vert_max = [(0, -1), (0, -2), (0, -3)]
hor_min = [(-1, 0), (-2, 0), (-3, 0)]
hor_max = [(1, 0), (2, 0), (3, 0)]
diag_min = [(1, 1), (2, 2), (3, 3)]
diag_max = [(-1, -1), (-2, -2), (-3, -3)]
other_diag_min = [(-1, 1), (-2, 2), (-3, 3)]
other_diag_max = [(1, -1), (2, -2), (3, -3)]
cord = {}
index = ["vert_min", "vert_max", "hor_min", "hor_max", "diag_min", "diag_max", "other_diag_min", "other_diag_max"]
cord["vert_min"] = vert_min
cord["vert_max"] = vert_max
cord["hor_min"] = hor_min
cord["hor_max"] = hor_max
cord["diag_min"] = diag_min
cord["diag_max"] = diag_max
cord["other_diag_min"] = other_diag_min
cord["other_diag_max"] = other_diag_max